version: '2.1'

services:
   rabbitmq:
      image: docker.io/bitnami/rabbitmq:3.9
      ports:
        - '4369:4369'
        - '5672:5672'
        - '25672:25672'
        - '15672:15672'
      environment:
        - RABBITMQ_SECURE_PASSWORD=yes
        - RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT=1G
        - RABBITMQ_USERNAME=test
        - RABBITMQ_PASSWORD=test
#      volumes:
#        - ./rabbitMQvolume:/bitnami
      healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3
